import                          os;
Import                          ('divaEnv');
Import                          ('shellEnv');

env = divaEnv.Copy              ();

env.Append                      (REF = Split ('#src/Diva.Util/util.dll \
                                               #src/Diva.Core/core.dll \
                                               #src/Diva.Basics/basics.dll \
                                               #src/Diva.PluginLib/pluginlib.dll \
                                               #src/Diva.Commands/commands.dll \
                                               #src/Diva.Widgets/widgets.dll'));

sources = Split                 ('AssemblyInfo.cs \
                                  Diva.Editor.Model.Root.cs \
                                  Diva.Editor.Model.Stuff.cs \
                                  Diva.Editor.Model.IModelPart.cs \
                                  Diva.Editor.Model.Args.cs \
                                  Diva.Editor.Model.Handlers.cs \
                                  Diva.Editor.Model.Pipeline.cs \
                                  Diva.Editor.Model.Export.cs \
                                  Diva.Editor.Model.Window.cs \
                                  Diva.Editor.Model.TaskProcessor.cs \
                                  Diva.Editor.Model.CommandProcessor.cs \
                                  Diva.Editor.Model.IStuffOrganizer.cs \
                                  Diva.Editor.Model.ByTagOrganizer.cs \
                                  Diva.Editor.Model.ByLengthOrganizer.cs \
                                  Diva.Editor.Model.ByTypeOrganizer.cs \
                                  Diva.Editor.Model.ByUsageOrganizer.cs \
                                  Diva.Editor.Model.StoreHelper.cs \
                                  Diva.Editor.Model.StuffTreeStore.cs \
                                  Diva.Editor.Model.Enums.cs \
                                  Diva.Editor.Model.Timeline.cs \
                                  Diva.Editor.Model.Debug.cs \
                                  Diva.Editor.Model.ToolSet.cs \
                                  Diva.Editor.Model.Tags.cs \
                                  Diva.Editor.Model.Clips.cs \
                                  Diva.Editor.Model.Tracks.cs \
                                  Diva.Editor.Model.ProjectDetails.cs \
                                  Diva.Editor.Model.MediaItems.cs \
                                  Diva.Editor.Model.MessageStack.cs \
                                  Diva.Editor.Model.CursorStack.cs \
                                  Diva.Editor.Model.Drag.cs');

assemblyInfo = shellEnv.Subst   ('AssemblyInfo.cs', '#common/AssemblyInfo.cs.in')

model = env.Dll                 ('editormodel.dll', sources);

env.Depends                     (model, assemblyInfo);

# INSTALL ######################################################################

Alias                           ("install", env.Install (os.path.join (env ['DESTDIR'], 
                                                                       env ['LIBDIR'],
                                                                       'diva'), model));
