import                          os;
Import                          ('CEnv');

# C ############################################################################

localEnvC = CEnv.Copy           ();
localEnvC.Append                (CPPPATH = Split ('. #src/Gdv/'),
				 CPPFLAGS = Split ('-g'),
                                 LIBS = Split ('gdv'));
            
sourcesC = Split                ('SourcePlayer.c');

seekplayer = localEnvC.Program  ('sourceplayer', sourcesC);

