import                          os;
Import                          ('divaEnv');
Import                          ('shellEnv');

env = divaEnv.Copy              ();

env.Append                      (REF = Split ('#src/Diva.Util/util.dll'),
                                 PKG = Split ('gconf-sharp-2.0'));

sources = Split                 ('AssemblyInfo.cs \
                                  Diva.Config.GConf.cs \
                                  Diva.Config.Projects.cs \
                                  Diva.Config.Ui.cs');

assemblyInfo = shellEnv.Subst   ('AssemblyInfo.cs', '#common/AssemblyInfo.cs.in');

config = env.Dll                ('config.dll', sources);

env.Depends                     (config, assemblyInfo);

# INSTALL ######################################################################

Alias                           ("install", env.Install (os.path.join (env ['DESTDIR'], 
                                                                       env ['LIBDIR'],
                                                                       'diva'), config));


