Import                          ('testEnv');

env = testEnv.Copy              ();

env.Append                      (REF = Split ('#src/Diva.Widgets/widgets.dll'));

sources = Split                 ('Diva.Widgets.Test.Exe.cs \
                                  Diva.Widgets.Test.Window.cs');

env.Exe                         ('widgetstest.exe', sources);
