import                          os;
Import                          ('divaEnv');
Import                          ('shellEnv');

env = divaEnv.Copy              ();

env.Append                      (REF = Split ('#src/Diva.Util/util.dll \
                                               #src/Diva.Widgets/widgets.dll \
                                               #src/Diva.Core/core.dll \
                                               #src/Diva.Commands/commands.dll \
                                               #src/Diva.Cairo/cairo.dll \
                                               #src/Diva.Basics/basics.dll \
                                               #src/Diva.Config/config.dll \
                                               #src/Diva.PluginLib/pluginlib.dll \
                                               #src/Diva.Editor.Model/editormodel.dll \
                                               #src/Diva.Editor.Timeline/editortimeline.dll'));

sources = Split                 ('AssemblyInfo.cs \
                                  Diva.Editor.Gui.Window.cs \
                                  Diva.Editor.Gui.MenuBar.cs \
                                  Diva.Editor.Gui.VideoFrame.cs \
                                  Diva.Editor.Gui.StuffVBox.cs \
                                  Diva.Editor.Gui.ExportWindow.cs \
                                  Diva.Editor.Gui.OrganizeByComboBox.cs \
                                  Diva.Editor.Gui.MediaControlsHBox.cs \
                                  Diva.Editor.Gui.StuffTreeView.cs \
                                  Diva.Editor.Gui.ZoomToComboBox.cs \
                                  Diva.Editor.Gui.TimelineVBox.cs \
                                  Diva.Editor.Gui.ToolToggleButton.cs \
                                  Diva.Editor.Gui.TimelineHScrollBar.cs \
                                  Diva.Editor.Gui.StatusHBox.cs \
                                  Diva.Editor.Gui.StripeHintDrawingArea.cs \
                                  Diva.Editor.Gui.CounterButton.cs \
                                  Diva.Editor.Gui.MessageArea.cs \
                                  Diva.Editor.Gui.SmallishToggleButton.cs \
                                  Diva.Editor.Gui.TogglesHBox.cs \
                                  Diva.Editor.Gui.SaveNagDialog.cs \
                                  Diva.Editor.Gui.MouseOverTimeLabel.cs \
                                  Diva.Editor.Gui.PipelineErrorDialog.cs \
                                  Diva.Editor.Gui.HistoryWindow.cs \
                                  Diva.Editor.Gui.JumpToWindow.cs \
                                  Diva.Editor.Gui.MoveToHBox.cs \
                                  Diva.Editor.Gui.HistoryTreeView.cs \
                                  Diva.Editor.Gui.StuffMenu.cs \
                                  Diva.Editor.Gui.TagCheckMenuItem.cs \
                                  Diva.Editor.Gui.EditTagDialog.cs \
                                  Diva.Editor.Gui.TagsWindow.cs \
                                  Diva.Editor.Gui.VolumeButton.cs \
                                  Diva.Editor.Gui.TagsTreeView.cs \
                                  Diva.Editor.Gui.VolumePopupWindow.cs \
                                  Diva.Editor.Gui.AboutDialog.cs \
                                  Diva.Editor.Gui.AlreadyImportedDialog.cs \
                                  Diva.Editor.Gui.PlayButton.cs');

assemblyInfo = shellEnv.Subst   ('AssemblyInfo.cs', '#common/AssemblyInfo.cs.in');

gui = env.Dll                   ('editorgui.dll', sources);

env.Depends                     (gui, assemblyInfo);

# INSTALL ######################################################################

Alias                           ("install", env.Install (os.path.join (env ['DESTDIR'], 
                                                                       env ['LIBDIR'],
                                                                       'diva'), gui));

