import                          os;
Import                          ('CEnv');

# C ############################################################################

localEnvC = CEnv.Clone          ();
localEnvC.Append                (CPPPATH = Split ('. #src/Gdv/'),
				 CPPFLAGS = Split ('-g'),
                                 LIBS = Split ('gdv'));
            
sourcesC = Split                ('ClipPlayer.c');

seekplayer = localEnvC.Program  ('clipplayer', sourcesC);

