import                          os;
Import                          ('divaEnv');
Import                          ('shellEnv');

env = divaEnv.Copy              ();

env.Append                      (REF = Split ('#src/Diva.Util/util.dll \
                                               #src/Diva.Widgets/widgets.dll \
                                               #src/Diva.Core/core.dll \
                                               #src/Diva.Commands/commands.dll \
                                               #src/Diva.Basics/basics.dll \
                                               #src/Diva.Cairo/cairo.dll \
                                               #src/Diva.Editor.Model/editormodel.dll'));

sources = Split                 ('AssemblyInfo.cs \
                                  Diva.Editor.Timeline.DrawingArea.cs \
                                  Diva.Editor.Timeline.Element.cs \
                                  Diva.Editor.Timeline.ElementList.cs \
                                  Diva.Editor.Timeline.ElementException.cs \
                                  Diva.Editor.Timeline.Enums.cs \
                                  Diva.Editor.Timeline.ViewElement.cs \
                                  Diva.Editor.Timeline.TrackLinesElement.cs \
                                  Diva.Editor.Timeline.LockElement.cs \
                                  Diva.Editor.Timeline.TimeStripesElement.cs \
                                  Diva.Editor.Timeline.RulerElement.cs \
                                  Diva.Editor.Timeline.ClipElement.cs \
                                  Diva.Editor.Timeline.OpacityMenuController.cs \
                                  Diva.Editor.Timeline.ClipPretenderElement.cs \
                                  Diva.Editor.Timeline.Tool.cs \
                                  Diva.Editor.Timeline.TrackElement.cs \
                                  Diva.Editor.Timeline.PanTool.cs \
                                  Diva.Editor.Timeline.OpacityTool.cs \
                                  Diva.Editor.Timeline.ZoomTool.cs \
                                  Diva.Editor.Timeline.ZoomAreaController.cs \
                                  Diva.Editor.Timeline.HighlightController.cs \
                                  Diva.Editor.Timeline.IMouseFollowController.cs \
                                  Diva.Editor.Timeline.EditTool.cs \
                                  Diva.Editor.Timeline.EditChainTool.cs \
                                  Diva.Editor.Timeline.CursorController.cs \
                                  Diva.Editor.Timeline.MoveController.cs \
                                  Diva.Editor.Timeline.IMovable.cs \
                                  Diva.Editor.Timeline.ITracking.cs \
                                  Diva.Editor.Timeline.IFloating.cs \
                                  Diva.Editor.Timeline.IDragController.cs \
                                  Diva.Editor.Timeline.DragController.cs \
                                  Diva.Editor.Timeline.CursorElement.cs \
                                  Diva.Editor.Timeline.CursorLineElement.cs \
                                  Diva.Editor.Timeline.ClipTrueElement.cs \
                                  Diva.Editor.Timeline.Helper.cs \
                                  Diva.Editor.Timeline.IRightClickController.cs \
                                  Diva.Editor.Timeline.IController.cs \
                                  Diva.Editor.Timeline.ClipMenuController.cs \
                                  Diva.Editor.Timeline.PanAreaController.cs \
                                  Diva.Editor.Timeline.ClipMenu.cs \
                                  Diva.Editor.Timeline.OpacityMenu.cs \
                                  Diva.Editor.Timeline.LeftAdjustController.cs \
                                  Diva.Editor.Timeline.ChainAdjustController.cs \
                                  Diva.Editor.Timeline.RightAdjustController.cs \
                                  Diva.Editor.Timeline.ILeftClickController.cs \
                                  Diva.Editor.Timeline.ILeftAdjustable.cs \
                                  Diva.Editor.Timeline.DragTool.cs \
                                  Diva.Editor.Timeline.CutTool.cs \
                                  Diva.Editor.Timeline.CutLineController.cs \
                                  Diva.Editor.Timeline.CutLineElement.cs \
                                  Diva.Editor.Timeline.IRightAdjustable.cs \
                                  Diva.Editor.Timeline.RulerSeekController.cs \
                                  Diva.Editor.Timeline.MoveAndTrackController.cs');

assemblyInfo = shellEnv.Subst   ('AssemblyInfo.cs', '#common/AssemblyInfo.cs.in')

timeline = env.Dll              ('editortimeline.dll', sources);

env.Depends                     (timeline, assemblyInfo);

# INSTALL ######################################################################

Alias                           ("install", env.Install (os.path.join (env ['DESTDIR'], 
                                                                       env ['LIBDIR'],
                                                                       'diva'), timeline));
