import                          os;
Import                          ('CEnv');

# C ############################################################################

localEnvC = CEnv.Clone          ();
localEnvC.Append                (CPPPATH = Split ('. #src/Gdv/'),
				 CPPFLAGS = Split ('-g'),
                                 LIBS = Split ('gdv'));
            
sourcesC = Split                ('TrackPlayer.c');

seekplayer = localEnvC.Program  ('trackplayer', sourcesC);

